### ISSUE TITLE
WX3270 Action EraseEOF() does not function

### ISSUE THREAD

**Issue by Peter-J-Jansen** [pmattes/Wx3270-New#22]
When assigning the "EraseEOF()" action to the END key, no errors are reported, but depressing the END key does not produce the 3270 "ERASE EOF" action; it merely moves to cursor to the end of the text in the concerned field.

As an alternative, I tried using the Key() action to assign "Alt-e" to the END key, but that also does not yield the desired result; I presume assigning any "Alt"-key combination is just not possible using the Key() action.  

Thanks,

Peter

**Comment by pmattes** [comment]
This is a known (and very annoying) issue with wx3270 keymaps. Both the End key and Alt-e are mapped by default to the FieldEnd() and EraseEOF() actions respectively. These default mappings specify 3270 mode. If your new mappings do not also specify 3270 mode, then they will not override the default mappings. This is because more-specific mappings take precedence over less-specific ones, and a mapping that specified 3270 mode is considered more specific than one that doesn't.

The easy workaround is to click on the '3270 mode' checkbox when specifying your key mappings.

I am working on making this clearer in wx3270 1.3, by displaying all of the mappings for the base key you have selected. That way you would see that End is mapped to FieldEnd() in 3270 mode. I can also remove the 3270-mode qualifier from many of the default mappings, since both FieldEnd() and EraseEOF() are no-ops if you are not in 3270 mode.

**Comment by Peter-J-Jansen** [comment]
Mr. Mattes,

Thanks for your speedy reply that resolved my problem by checking the '3270 mode' checkbox. This solution is absolutely fine for me.

Cheers,

Peter

**Comment by pmattes** [comment]
Excellent!
